[tool.poetry]
name = "robot-results"
version = "0.1.0"
description = ""
authors = ["tomek"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
robotframework = "6.*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
